# Streamlit secrets configuration file
# Store sensitive credentials here - this file should NOT be committed to version control

# Google OAuth Configuration
[google_oauth]
client_id = "YOUR_GOOGLE_CLIENT_ID_HERE"
client_secret = "YOUR_GOOGLE_CLIENT_SECRET_HERE"
redirect_uri = "http://localhost:8501"  # Update for production deployment

# Development Mode - Set to true to enable test login buttons
dev_mode = true

# OpenAI API Configuration (existing)
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY_HERE"

# Google Sheets Service Account Credentials (existing)
# Replace with your actual service account JSON
CREDENTIALS_JSON = '''
{
  "type": "service_account",
  "project_id": "your-project-id",
  "private_key_id": "your-private-key-id",
  "private_key": "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----\n",
  "client_email": "your-service-account@your-project.iam.gserviceaccount.com",
  "client_id": "your-client-id",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "your-cert-url"
}
'''

# User Management Settings (for reference - actual allowlist is in auth.py)
# Authorized users:
# - 42expelliarmus@gmail.com (admin)
# - mx.anderson15@gmail.com (staff)

# Future domain restriction (currently commented in code):
# allowed_domain = "@conceptionnurseries.com"